### ISSUE TITLE
unable to create dailyfile on windows

### ISSUE THREAD

**Issue by meekaah** [baryon/tracer#101]
Hi there,
there was a commit (#77 ) that was supposed to fix a bug where the daily file couldnt be created on windows and the workaround was to use mkdirp unfortunetly the call made is async and causes another timing issue. My guess for a viable workaround would be to make use of [mkdirp.sync(dir, opts)](https://github.com/substack/node-mkdirp#mkdirpsyncdir-opts).

Unfortunetly i'm not sure I have 100% repro steps so can't really know for SURE. In the mean time i've made a workaround in our code to create the directory structure before the dailyfile is created.

**Comment by baryon** [comment]
I have not Windows PC to test this issue. welcome donate code fix it
