### ISSUE TITLE
Performance issues when using file name and line number

### ISSUE THREAD

**Issue by vishwasrao** [baryon/tracer#108]
Hi,
We are exploring this package for our project.

In most of discussions below, getting file name and line number is not easy and has performance impact.
It needs to create error stack object and iterate it through to get file name and line number.

Are we using same logic to get file name and line number?
Is there any matrics of performance when using this package?

References:
https://stackoverflow.com/questions/14172455/get-name-and-line-of-calling-function-in-node-js
https://stackoverflow.com/questions/14172455/get-name-and-line-of-calling-function-in-node-js/53339452
https://stackoverflow.com/questions/46630800/nodejs-print-function-name-line-number-and-file-name?rq=1
https://stackoverflow.com/questions/45395369/how-to-get-console-log-line-numbers-shown-in-nodejs

**Comment by baryon** [comment]
we use stack info like these discuss
here is a stress test example
https://github.com/baryon/tracer/blob/master/example/stress.js

please set log level in production env
