### ISSUE TITLE
update mkdirp (containing vulnerability of old minimist)

### ISSUE THREAD

**Issue by DominikStransky** [baryon/tracer#112]
See:
https://www.npmjs.com/advisories/1179
https://github.com/isaacs/node-mkdirp/issues/9
https://david-dm.org/baryon/tracer?view=list

Thanks in advance!

**Comment by plade** [comment]
Created a PR here: https://github.com/baryon/tracer/pull/113

**Comment by baryon** [comment]
Thanks
