### ISSUE TITLE
In `transport`, `data` seems having not enough values

### ISSUE THREAD

**Issue by eouia** [baryon/tracer#118]
```js
  transport: function (data) {
    console.log(data)
    // I want to send specific log data to remote server like `path` and `line`, but empty. 
  },
```

![image](https://user-images.githubusercontent.com/1720610/82466895-41b57c80-9ac1-11ea-86d2-aceae7481a94.png)

Maybe I might parse `output` itself, but not so graceful approach.

**Comment by baryon** [comment]
maybe you set level is higher than info in config

2020年5月21日(木) 0:42 Seongnoh Sean Yi <notifications@github.com>:

**Comment by eouia** [comment]
I think I found something. When I use `format`, the `data` would have missed some values.

![image](https://user-images.githubusercontent.com/1720610/82470099-306e6f00-9ac5-11ea-98cc-5191de436d3d.png)


Result:
![image](https://user-images.githubusercontent.com/1720610/82470197-53991e80-9ac5-11ea-9b65-162d4dda3cb1.png)

**Comment by eouia** [comment]
Hmmm.. closed? Is this normal behavior?

**Comment by baryon** [comment]
Yes, if don't need stack info in format, it don't generate these.

**Comment by eouia** [comment]
Ok. Thanks for confirming.
