### ISSUE TITLE
Multiple Transports

### ISSUE THREAD

**Issue by DaAwesomeP** [baryon/tracer#12]
Is it possible to use multiple transports? I have tried multiple thing but I can't seem to get it to work. Please provide an example.

**Comment by nexflo** [comment]
Yup +1 on this. lookin for exactly the same. 
@DaAwesomeP solutions are both the way to go!

**Comment by AmitThakkar** [comment]
+1

**Comment by AmitThakkar** [comment]
If I am using 1`dailyfile`, then it by default write on file only, there is no way to log message on console as well, If there will be support of multiple transport, then we can print on console as well.

**Comment by AmitThakkar** [comment]
Added a pull request for the same at [https://github.com/baryon/tracer/pull/36](https://github.com/baryon/tracer/pull/36). Please have a look.

**Comment by AmitThakkar** [comment]
I think, now we can mark as resolved!

**Comment by baryon** [comment]
Thanks AmitThakkar, updated v0.8.1

**Comment by DaAwesomeP** [comment]
Cool!

**Comment by Leshich** [comment]
It's not clear for me how to use daily logs + console output for 1 logger.
Can you explain, @AmitThakkar ?:)

btw, it would be better if i could set it up like @DaAwesomeP suggested with 2nd solution.

**Comment by AmitThakkar** [comment]
@Leshich That was just an example, In my use case, we are using daily file log and sending mail in case of error and doing other stuff, but with current implementation we can't provide multiple logger with daily log.
