### ISSUE TITLE
What is the status of this project? Is it being actively maintained?

### ISSUE THREAD

**Issue by robert-gruner** [baryon/tracer#127]
Hi @baryon,

first of all a big thanks for this useful library. I've been using it in some business projects and it was very easy to use.

I've seen that the last release was quite a while ago und that there are some dependabot PRs pending. So I wanted to check in on the state of the project. There are some questions to help us decide if we can keep on relying on this lib in our production codebases:

- Can we assume that there is active maintenance? I am talking about keeping the dependencies up to date, e.g. tinytim.
- Do you consider this library "feature" complete?
- Do you yourself use the lib in productive applications?

Thanks in advance for your answer.

All the best,
Robert

**Comment by baryon** [comment]
yes. The lib was used in the many projects of our company . I will check
depends and update soon.

Best regards
Long Li

2021年6月3日(木) 23:20 Robert Gruner ***@***.***>:

**Comment by robert-gruner** [comment]
Alright, thanks for the info.
