### ISSUE TITLE
Request for a new log level of "off" to disable all logging output

### ISSUE THREAD

**Issue by mariobianco** [baryon/tracer#129]
First off, great library. I'm really enjoying it.

Apologies if this feature request already exists but I wasn't able to discover if it did.

What I would like to request is a new log level of `off` so that we can disable any `logger.x()` methods from printing.

For example, given the following code:
```
logger.log('log level')
logger.trace('trace level')
logger.debug('debug level')
logger.info('info level')
logger.warn('warn level')
logger.error('error level')
logger.fatal('fatal level')
```
The current highest capability we have of turning something "off" is setting it to `fatal` which greatly minimizes output, but does not completely turn logging off.

It would be awesome if we could completely disable the `logger` via:
```
tracer.setLevel('off')
```

_I'm currently using `"tracer": "^1.1.5"`._

**Comment by baryon** [comment]
try set level to a big number 
ex:
```
{
level: 100
}
```

**Comment by mariobianco** [comment]
Awesome, thanks for that speedy reply!

You are correct, the logging will not print if we set the log level to `10` or something greater, e.g. this disables all log output:
```
tracer.setLevel(10)
```

In case anyone else comes across this request, I'll post what I ended up doing in TypeScript. _(Disclaimer, the below code snippet might have bugs since I modified it for just this post.)_

```typescript
// Within the './logger.ts' module
enum logLevels {
  log = 0,
  trace = 1,
  debug = 2,
  info = 3,
  warn = 4,
  error = 5,
  fatal = 6,
  off = 999
}
export type LogLevels = keyof typeof logLevels

// Within the './consumer.ts' module
import { logLevels, LogLevels } from './logger'
const consumerLogLevel: LogLevels = 'off'
tracer.setLevel(logLevels[consumerLogLevel]) // need to set it via its numerical form since tracer does not know what the string of 'off' means
```
