### ISSUE TITLE
replace default console

### ISSUE THREAD

**Issue by haikyuu** [baryon/tracer#29]
Can i replace the default console in order to use `console.log` normally and not have to require logger in every file ?

**Comment by baryon** [comment]
Sure, I think the <a href="https://nodejs.org/api/globals.html#globals_global_objects">global namespace object</a> is works

example:
aa.js
```javascript
var bb = require('./bb')
global.logger = require('tracer').console();

logger.log('hello');
logger.trace('hello', 'world');
logger.debug('hello %s', 'world', 123);
logger.warn('hello %s', 'world', 123);
logger.error('hello %s', 'world', 123);

bb.hi()

```

bb.js
```javascript
exports.hi = function() {
	logger.log('hello');
	logger.trace('hello', 'world');
	logger.debug('hello %s', 'world', 123);
	logger.warn('hello %s', 'world', 123);
	logger.error('hello %s', 'world', 123);
}


```

**Comment by haikyuu** [comment]
Thanks, I've never used `global` before. :+1:

**Comment by zhoukekestar** [comment]
@baryon `global.logger = require('tracer').console();`  Is this the best practice.

**Comment by baryon** [comment]
I use normally const console = require('tracer').console();
keke <notifications@github.com>于2017年6月8日 周四下午5:54写道：
