### ISSUE TITLE
Dynamical log level

### ISSUE THREAD

**Issue by madarche** [baryon/tracer#30]
Hello @baryon, would you be interested in a PR that would make it possible to dynamically change the log level of a logger?

Something like `logger.setLevel(level)`

I really miss this feature in tracer.

Cheers

**Comment by baryon** [comment]
I added setLevel and close methods in v0.8.0, please check it, thanks

**Comment by madarche** [comment]
@baryon thanks a lot for the addition of `setLevel`! I've just integrated it today and it works great for our projects!

Just one small remark about the notice "if you set level in initialize, you can't change more lower level than the initial level". Could you explain why you have made this [choice in the code](https://github.com/baryon/tracer/blob/master/lib/console.js#L15), what is the rationale of this limitation please?
