### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by herkyl** [baryon/tracer#44]
I had a memory leak in my application and after further investigation it seems that `tracer` was causing it. I am using the colorConsole like this:

```javascript
require('tracer').colorConsole({
  format: '{{timestamp}} <{{title}}> {{message}} (in {{file}}:{{line}})',
  dateformat: 'HH:MM:ss.L',
  level: config.LOG_LEVEL
});
```
I don't have more information atm but after turning off logging the leak has stopped.
The leak is pretty major as it is constantly eating up gigs on my productions servers on warn level.

**Comment by baryon** [comment]
how to detect memory leak by you.
I tested, can't found a point

**Comment by herkyl** [comment]
I debugged the app using [node-inspector](https://github.com/node-inspector/node-inspector) and used heap snapshots to see what has happened after logging a lot (try doing 100k log calls).

**Comment by baryon** [comment]
I can't capture continual growth of memory.

`node-debug example/stress.js` 

pending

**Comment by herkyl** [comment]
I will check it out later

**Comment by baryon** [comment]
any problem, reopen please
