### ISSUE TITLE
Transport: Data Output and Text Logs

### ISSUE THREAD

**Issue by pixelshaded** [baryon/tracer#5]
Not sure which direction this should go. So the examples for transport files use the output object to write. The output object includes color markup though.

Example from the data object:

output: '\u001b[36mdebug > environment.js [140]: Send Ok to Client: {"userID":111,"status":"ok"}\u001b[39m'

So we have \u001b[1m\u001b[36m at the start, and \u001b[39m\u001b[22m at the end. These end up in the logs and make them much harder to read. I imagine this is used for stdout, but it's not so great text files. I could recreate the formatting using the data object, but that kinda defeats the purpose of creating a format string in the settings.

Are there text formats that will interpret the color portions of the output?

**Comment by Royalgamer06** [comment]
Why is this closed? Shouldn't there be a way to use colors for console, while being able to write the log WITHOUT color tags to a file?

**Comment by Royalgamer06** [comment]
Maybe add another property to the data object: Output without color tags?
