### ISSUE TITLE
can not remove old files on windows?

### ISSUE THREAD

**Issue by jiaozebo** [baryon/tracer#59]
I've gotten too many files in my log directory(I'm using daily log), it did not looks like the tracer has removed any file(the maxLogFiles has been set to 10). 

so for confirm, i debug the code, this line did executed, but not working.
`spawn('find', ['./', '-type', 'f', '-name', '*.log', '-mtime', '+' + _conf.maxLogFiles, '-exec', 'rm', '{}', '\;']);`

i'm on windows.

**Comment by jiaozebo** [comment]
BTW the version is 0.8.3

 tracer@0.8.3 node_modules\tracer
├── tinytim@0.1.1
├── colors@1.0.3
└── dateformat@1.0.11 (get-stdin@5.0.1, meow@3.7.0)

**Comment by baryon** [comment]
was the issue fixed? just close
