### ISSUE TITLE
Follow sourcemaps to calculate line number

### ISSUE THREAD

**Issue by ubenzer** [baryon/tracer#60]
Hi!
I started using tracer in my project and it is super useful. 

In my project, I am using typescript. Tracer calculates and shows line numbers in javascript and does not follow sourcemaps. That would be awesome to see `index.ts:12` instead of `index.js:50`

I wonder if this is possible (to add this to core library as a feature) or can I somehow extend this library with my additions to do this?

Any kind of leads would be awesome. 🎉🎉

**Comment by osharper** [comment]
I believe [source-map-support](https://www.npmjs.com/package/source-map-support) might do the trick

**Comment by baryon** [comment]
I dont use typescript, need help and a "pull request"

**Comment by osharper** [comment]
@baryon I don't really think that this issue refers to your library. Of course you can somehow integrate the ideas from source-map-support to the tracer but I strongly believe that everyone should do it's own job. It also seems like @ubenzer is happy with my answer. I'm using typescript for years and source-map-support package works just fine for me with any logger.

**Comment by ubenzer** [comment]
Hi! 

I agree that this has nothing to do with logging and shouldn't be added to this library. I made it working by using `source-map`.

An sample implementation [can be found here](https://github.com/ubenzer/fil-old/blob/master/app/lib/logger.ts#L20) in case anyone else interested in the future. :-)
