### ISSUE TITLE
Not compatible with node.js's console

### ISSUE THREAD

**Issue by tangxinfa** [baryon/tracer#63]
[Node.js 's console](https://nodejs.org/docs/latest-v4.x/doc/api/console.html):

    console.log
        Prints to stdout with newline
    console.info
        Same as console.log.
    console.error
        Same as console.log but prints to stderr.
    console.warn
        Same as console.error.

[Tracer's console](https://github.com/baryon/tracer/blob/master/lib/console.js):

    transport : function(data) {
        console.log(data.output);
    }

This mean's when use tracer, all logging output write to stdout, we can't split message in shell now:

    node app.js > ./app.out.log 2>./app.err.log

[Buyan](https://github.com/trentm/node-bunyan)'s no problem:

    ConsoleRawStream.prototype.write = function (rec) {
       if (rec.level < INFO) {
           console.log(rec);
       } else if (rec.level < WARN) {
           console.info(rec);
       } else if (rec.level < ERROR) {
           console.warn(rec);
      } else {
           console.error(rec);
       }
     };

**Comment by timaschew** [comment]
This is a dealbreaker!
