### ISSUE TITLE
How do you get file and line value in my current Typescript project setup?

### ISSUE THREAD

**Issue by JasonShin** [baryon/tracer#78]
Project location:

https://gitlab.com/biphub/biphub

What I am getting at the moment:

![logg](https://user-images.githubusercontent.com/2525002/31573538-c553229e-b109-11e7-9583-c0bf0743170c.PNG)

Logger source code

https://gitlab.com/biphub/biphub/blob/master/core/logger/index.ts

I'm using an example usage of tracer in Typescript found here https://github.com/ubenzer/fil-old/blob/master/app/lib/logger.ts#L20

I am not too sure what I am doing wrong because sourcemap is working correctly that's why tsc is picking it up and printing it on the terminal. Please let me know if you can identify what is wrong with the current set up.

**Comment by sgoff0** [comment]
For those like myself that come here many years later, I found one line of code, simply importing
```js
import 'source-map-support/register'
```
per https://www.npmjs.com/package/source-map-support solved this problem for me.  Now instead of tracer logging out javascript files and line numbers, I see typescript files and line numbers.
