### ISSUE TITLE
Do your guys has plan to implement tracer.table just like console.table?

### ISSUE THREAD

**Issue by sirius1024** [baryon/tracer#86]
Do your guys has plan to implement tracer.table just like console.table?

https://developer.mozilla.org/en-US/docs/Web/API/Console/table

https://nodejs.org/dist/latest-v10.x/docs/api/console.html#console_console_table_tabulardata_properties

**Comment by baryon** [comment]
Good Idea. in v0.9.0, all console methods was supported. Thanks.

**Comment by sirius1024** [comment]
@baryon Well done! I've upgrade to 0.9, Thanks for your great work!
