### ISSUE TITLE
Support for ndjson?

### ISSUE THREAD

**Issue by kaihendry** [baryon/tracer#91]
How do make sure messages are not broken between lines like:

```
I20181105-12:40:44.285(8)? {timestamp: '2018-11-05T12:40:44+0800', title: 'info', file: 'comments.js', line:'67', method: 'MethodInvocation.comments.insert', message: 'test@dev.unee-t.com is commenting "yayyy
I20181105-12:40:44.285(8)? " on case 1' }
```

I'm using the following configuration:
https://github.com/unee-t/frontend/blob/6aed066174f565c0982efd1d46aebb746f962149/imports/util/logger.js

My end goal is query logs with AWS CloudWatch using their JSON query language, which IIUC supports http://ndjson.org/

**Comment by baryon** [comment]
updated a sample
https://github.com/baryon/tracer/blob/master/example/formatJson.js

**Comment by kaihendry** [comment]
Don't quite understand the code. How would I toggle between no tracing for process.env.STAGE is unset and using tracing when it is?
