### ISSUE TITLE
JSON key: value coloring?

### ISSUE THREAD

**Issue by jgentes** [baryon/tracer#95]
Tracer works well, and I was hoping the JSON objects would use coloring similar to what you see with util.inspect. Any way to do this? I've tried applying formatting but haven't been able to manage it with jsome or other modules due to the way tracer injects it's own color formatting.

Here's what I'm hoping for:

![image](https://user-images.githubusercontent.com/1149470/49343579-f1becd80-f620-11e8-805d-11fb34dd9abb.png)

**Comment by baryon** [comment]
we must write a transport function like https://github.com/baryon/tracer/blob/master/example/formatJson.js

and add color to value,
require('colors')

**Comment by jgentes** [comment]
@baryon Thanks for your reply, I just had a chance to try it.

Coloring the value of `data.message` only provides a single color for the entire JSON block. I want to retain my format configuration, but automatically color key/value pairs when JSON is used in the message:

```
tracer.colorConsole({
  format: '{{file}}:{{line}} {{title}}' + (Env.PROD ? '' : '\u001b[0m') + '{{message}}',
  preprocess: data => {
    // catch log.error and send to bugnsag
    if (data.title === 'error') bugsnagClient.notify(new Error(data.stack));
    data.title = '';
  },
  transport: function(data) {
    console.log({
      timestamp: data.timestamp,
      title: data.title,
      file: data.file,
      line: data.line,
      method: data.method,
      message: data.message
    });
  }
});
```

**Comment by broofa** [comment]
Adding `inspectOpts: {color: true}` to the config turns on colorizing of object keys and values.
