### ISSUE TITLE
add `rootDir` config

### ISSUE THREAD

**Issue by nswbmw** [baryon/tracer#99]
I think `test/app.js` is nice(but enough) than `/Users/nswbmw/Desktop/test/app.js`, so I bumped [tracer2](https://github.com/nswbmw/tracer2) before tracer@0.9.1, added `rootDir` config.

If you added this config, i will deprecated tracer2. :)

**Comment by baryon** [comment]
Great, Could you pull the codes

**Comment by baryon** [comment]
merged. see example folder.js and folder2.js
